[package]
name = "cycling-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { version = "0.11", features = ["tls"] }
tonic-reflection = "0.11.0"
prost = "0.12"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "sync", "time"] }
tokio-stream = "0.1"
async-stream = "0.3.5"
tonic-types = "0.11.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
anyhow = "1.0.86"
thiserror = "1.0.62"

[build-dependencies]
tonic-build = "0.11"
