name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  PROTOC_VERSION: 3.25.1
  DATABASE_URL: sqlite:ct.db

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install protoc
      uses: taiki-e/install-action@v2
      with:
        tool: protoc@${{ env.PROTOC_VERSION }}
    - name: Install SQLx CLI
      run: cargo install --version=0.8.0 sqlx-cli --no-default-features --features sqlite
    - name: Prepare database
      run: |
        sqlx database create
        sqlx migrate run
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
